# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wid_ControleMoteur_v3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_moteur_template(object):
    def setupUi(self, moteur_template):
        moteur_template.setObjectName("moteur_template")
        moteur_template.resize(543, 140)
        self.But_Velocity = QtWidgets.QPushButton(moteur_template)
        self.But_Velocity.setGeometry(QtCore.QRect(410, 90, 21, 20))
        self.But_Velocity.setObjectName("But_Velocity")
        self.lineEdit_Velocity = QtWidgets.QLineEdit(moteur_template)
        self.lineEdit_Velocity.setGeometry(QtCore.QRect(330, 90, 80, 20))
        self.lineEdit_Velocity.setText("")
        self.lineEdit_Velocity.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Velocity.setObjectName("lineEdit_Velocity")
        self.label_2 = QtWidgets.QLabel(moteur_template)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 51, 20))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(moteur_template)
        self.label_6.setGeometry(QtCore.QRect(330, 50, 81, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_Target = QtWidgets.QLineEdit(moteur_template)
        self.lineEdit_Target.setGeometry(QtCore.QRect(330, 70, 80, 20))
        self.lineEdit_Target.setText("")
        self.lineEdit_Target.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Target.setObjectName("lineEdit_Target")
        self.But_Home = QtWidgets.QPushButton(moteur_template)
        self.But_Home.setGeometry(QtCore.QRect(330, 20, 75, 20))
        self.But_Home.setObjectName("But_Home")
        self.lineEdit_InformationMoteur = QtWidgets.QLineEdit(moteur_template)
        self.lineEdit_InformationMoteur.setGeometry(QtCore.QRect(20, 20, 290, 20))
        self.lineEdit_InformationMoteur.setReadOnly(True)
        self.lineEdit_InformationMoteur.setObjectName("lineEdit_InformationMoteur")
        self.But_FastPosStep = QtWidgets.QPushButton(moteur_template)
        self.But_FastPosStep.setGeometry(QtCore.QRect(210, 90, 70, 20))
        self.But_FastPosStep.setObjectName("But_FastPosStep")
        self.But_Fermer = QtWidgets.QPushButton(moteur_template)
        self.But_Fermer.setGeometry(QtCore.QRect(460, 50, 60, 60))
        self.But_Fermer.setObjectName("But_Fermer")
        self.lcdNum_Position = QtWidgets.QLCDNumber(moteur_template)
        self.lcdNum_Position.setGeometry(QtCore.QRect(420, 20, 100, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.lcdNum_Position.setPalette(palette)
        self.lcdNum_Position.setObjectName("lcdNum_Position")
        self.lineEdit_StepSize = QtWidgets.QLineEdit(moteur_template)
        self.lineEdit_StepSize.setGeometry(QtCore.QRect(110, 73, 90, 20))
        self.lineEdit_StepSize.setText("")
        self.lineEdit_StepSize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StepSize.setObjectName("lineEdit_StepSize")
        self.label_9 = QtWidgets.QLabel(moteur_template)
        self.label_9.setGeometry(QtCore.QRect(420, 0, 101, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(moteur_template)
        self.label.setGeometry(QtCore.QRect(26, 110, 81, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.But_PosStep = QtWidgets.QPushButton(moteur_template)
        self.But_PosStep.setGeometry(QtCore.QRect(210, 73, 50, 20))
        self.But_PosStep.setObjectName("But_PosStep")
        self.label_7 = QtWidgets.QLabel(moteur_template)
        self.label_7.setGeometry(QtCore.QRect(330, 110, 81, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(moteur_template)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 281, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.But_Target = QtWidgets.QPushButton(moteur_template)
        self.But_Target.setGeometry(QtCore.QRect(410, 70, 20, 20))
        self.But_Target.setObjectName("But_Target")
        self.But_FastNegStep = QtWidgets.QPushButton(moteur_template)
        self.But_FastNegStep.setGeometry(QtCore.QRect(30, 90, 70, 20))
        self.But_FastNegStep.setObjectName("But_FastNegStep")
        self.But_NegStep = QtWidgets.QPushButton(moteur_template)
        self.But_NegStep.setGeometry(QtCore.QRect(50, 73, 50, 20))
        self.But_NegStep.setObjectName("But_NegStep")
        self.label_5 = QtWidgets.QLabel(moteur_template)
        self.label_5.setGeometry(QtCore.QRect(106, 110, 101, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(moteur_template)
        self.label_4.setGeometry(QtCore.QRect(210, 110, 71, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_FastStepSize = QtWidgets.QLineEdit(moteur_template)
        self.lineEdit_FastStepSize.setGeometry(QtCore.QRect(110, 90, 90, 20))
        self.lineEdit_FastStepSize.setText("")
        self.lineEdit_FastStepSize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FastStepSize.setObjectName("lineEdit_FastStepSize")

        self.retranslateUi(moteur_template)
        QtCore.QMetaObject.connectSlotsByName(moteur_template)

    def retranslateUi(self, moteur_template):
        _translate = QtCore.QCoreApplication.translate
        moteur_template.setWindowTitle(_translate("moteur_template", "Form"))
        self.But_Velocity.setText(_translate("moteur_template", "->"))
        self.label_6.setText(_translate("moteur_template", "Target (mm)"))
        self.But_Home.setText(_translate("moteur_template", "Home"))
        self.But_FastPosStep.setText(_translate("moteur_template", ">>"))
        self.But_Fermer.setText(_translate("moteur_template", "Fermer"))
        self.label_9.setText(_translate("moteur_template", "Actual position"))
        self.label.setText(_translate("moteur_template", "Fast Neg Step"))
        self.But_PosStep.setText(_translate("moteur_template", ">"))
        self.label_7.setText(_translate("moteur_template", "Velocity"))
        self.label_8.setText(_translate("moteur_template", "Motor information"))
        self.But_Target.setText(_translate("moteur_template", "->"))
        self.But_FastNegStep.setText(_translate("moteur_template", "<<"))
        self.But_NegStep.setText(_translate("moteur_template", "<"))
        self.label_5.setText(_translate("moteur_template", "Step (µm)"))
        self.label_4.setText(_translate("moteur_template", "Fast Pos Step"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    moteur_template = QtWidgets.QWidget()
    ui = Ui_moteur_template()
    ui.setupUi(moteur_template)
    moteur_template.show()
    sys.exit(app.exec_())

